server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: mfa
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML
    suffix: .html

logging:
  level:
    root: info
    com.mfa: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace
